# Generated by Django 4.0.4 on 2022-05-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_closet_alter_answer_question_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='closet',
            name='mainphoto',
        ),
    ]
