# Generated by Django 4.0.4 on 2022-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_closet_contents_remove_closet_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='contents',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closet',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
