# Generated by Django 4.0.4 on 2022-05-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_closet_contents_closet_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='contents',
        ),
    ]
